name: cryptocoin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  liquid_pull_to_refresh: ^2.0.0
  font_awesome_flutter: ^8.11.0
  local_auth: ^0.6.3+4
  fl_chart:
  http:
  flutter_svg:
  cached_network_image:
  intl:
  flutter_web_browser:
  focused_menu:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/icon.png
  uses-material-design: true
